using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Fakvio.Infrastructure.Migrations.Tenant
{
    /// <summary>
    /// Adds ChatConversation and ChatMessage tables for the AI chat feature.
    ///
    /// Why raw SQL with "IF NOT EXISTS"?
    /// ----------------------------------
    /// Existing tenants were provisioned with earlier migrations that have since been
    /// squashed into InitTenant. When MigrateAsync runs on those tenants, InitTenant
    /// is seen as a new migration but fails because most tables already exist — so the
    /// new chat tables (included in InitTenant) never get created either.
    ///
    /// This migration uses CREATE TABLE IF NOT EXISTS so it is safe for BOTH:
    ///   - New tenants: tables already exist from InitTenant → no-op
    ///   - Existing tenants: tables are missing → created here
    ///
    /// Junior note: "IF NOT EXISTS" means PostgreSQL will skip the CREATE if the table
    /// is already there, preventing "relation already exists" errors.
    /// </summary>
    public partial class AddChatTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── ChatConversation ──────────────────────────────────────────────────
            // Stores AI chat conversations per user per tenant.
            // UserId references User in the master schema (cross-schema, no FK).
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ChatConversation"" (
                    ""Id""              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId""          bigint NOT NULL,
                    ""Title""           character varying(200) NOT NULL,
                    ""LastMessageAt""   timestamp with time zone NOT NULL,
                    ""IsArchived""      boolean NOT NULL DEFAULT false,
                    ""CreatedAt""       timestamp with time zone NOT NULL,
                    ""UpdatedAt""       timestamp with time zone,
                    ""CreatedByUserId"" bigint,
                    ""UpdatedByUserId"" bigint
                );
            ");

            // Indexes for ChatConversation (IF NOT EXISTS prevents duplicates)
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ChatConversation_UserId_LastMessageAt""
                    ON ""ChatConversation"" (""UserId"", ""LastMessageAt"");
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ChatConversation_IsArchived""
                    ON ""ChatConversation"" (""IsArchived"");
            ");

            // ── ChatMessage ───────────────────────────────────────────────────────
            // Stores individual messages within a chat conversation.
            // Role is stored as int: 0=System, 1=User, 2=Assistant.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ChatMessage"" (
                    ""Id""              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ConversationId""  bigint NOT NULL,
                    ""Role""            integer NOT NULL,
                    ""Content""         text NOT NULL,
                    ""ProviderUsed""    character varying(50),
                    ""TokensUsed""      integer,
                    ""CreatedAt""       timestamp with time zone NOT NULL,
                    ""UpdatedAt""       timestamp with time zone,
                    ""CreatedByUserId"" bigint,
                    ""UpdatedByUserId"" bigint,
                    CONSTRAINT ""FK_ChatMessage_ChatConversation_ConversationId""
                        FOREIGN KEY (""ConversationId"")
                        REFERENCES ""ChatConversation"" (""Id"")
                        ON DELETE CASCADE
                );
            ");

            // Index for ChatMessage (IF NOT EXISTS prevents duplicates)
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ChatMessage_ConversationId""
                    ON ""ChatMessage"" (""ConversationId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop in reverse order due to FK dependency
            migrationBuilder.DropTable(name: "ChatMessage");
            migrationBuilder.DropTable(name: "ChatConversation");
        }
    }
}
