// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.CloudStorageController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.CloudStorage;
using Fakvio.Domain.Enums;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping CloudStorageController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class CloudStorageFunctions
{
    private readonly CloudStorageController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public CloudStorageFunctions(CloudStorageController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/cloud-storage/status → CloudStorageController.GetStatus
    /// </summary>
    [Function("CloudStorage_GetStatus")]
    public async Task<IActionResult> CloudStorage_GetStatus(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/cloud-storage/status")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetStatus(ct));
    }

    /// <summary>
    /// GET api/cloud-storage/auth-url → CloudStorageController.GetAuthorizationUrl
    /// </summary>
    [Function("CloudStorage_GetAuthorizationUrl")]
    public async Task<IActionResult> CloudStorage_GetAuthorizationUrl(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/cloud-storage/auth-url")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?provider=Value
        Enum.TryParse(req.Query["provider"].ToString(), true, out global::Fakvio.Domain.Enums.ECloudStorageProvider provider);
        string redirectUri = req.Query["redirectUri"].ToString() ?? "";
        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetAuthorizationUrl(provider, redirectUri, ct));
    }

    /// <summary>
    /// POST api/cloud-storage/callback → CloudStorageController.ExchangeCode
    /// </summary>
    [Function("CloudStorage_ExchangeCode")]
    public async Task<IActionResult> CloudStorage_ExchangeCode(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/cloud-storage/callback")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?provider=Value
        Enum.TryParse(req.Query["provider"].ToString(), true, out global::Fakvio.Domain.Enums.ECloudStorageProvider provider);
        string code = req.Query["code"].ToString() ?? "";
        string redirectUri = req.Query["redirectUri"].ToString() ?? "";
        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.ExchangeCode(provider, code, redirectUri, ct));
    }

    /// <summary>
    /// POST api/cloud-storage/disconnect → CloudStorageController.Disconnect
    /// </summary>
    [Function("CloudStorage_Disconnect")]
    public async Task<IActionResult> CloudStorage_Disconnect(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/cloud-storage/disconnect")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?provider=Value
        Enum.TryParse(req.Query["provider"].ToString(), true, out global::Fakvio.Domain.Enums.ECloudStorageProvider provider);
        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.Disconnect(provider, ct));
    }

    /// <summary>
    /// GET api/cloud-storage/folders → CloudStorageController.ListFolders
    /// </summary>
    [Function("CloudStorage_ListFolders")]
    public async Task<IActionResult> CloudStorage_ListFolders(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/cloud-storage/folders")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?provider=Value
        Enum.TryParse(req.Query["provider"].ToString(), true, out global::Fakvio.Domain.Enums.ECloudStorageProvider provider);
        string? parentId = req.Query.TryGetValue("parentId", out var _parentIdVal) ? _parentIdVal.ToString() : null;
        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.ListFolders(provider, parentId, ct));
    }

    /// <summary>
    /// POST api/cloud-storage/set-folder → CloudStorageController.SetFolder
    /// </summary>
    [Function("CloudStorage_SetFolder")]
    public async Task<IActionResult> CloudStorage_SetFolder(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/cloud-storage/set-folder")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?provider=Value
        Enum.TryParse(req.Query["provider"].ToString(), true, out global::Fakvio.Domain.Enums.ECloudStorageProvider provider);
        // Deserialize request body → CloudStorageSetFolderRequest
        var request = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.CloudStorage.CloudStorageSetFolderRequest>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.SetFolder(provider, request!, ct));
    }

    /// <summary>
    /// POST api/cloud-storage/test → CloudStorageController.TestConnection
    /// </summary>
    [Function("CloudStorage_TestConnection")]
    public async Task<IActionResult> CloudStorage_TestConnection(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/cloud-storage/test")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?provider=Value
        Enum.TryParse(req.Query["provider"].ToString(), true, out global::Fakvio.Domain.Enums.ECloudStorageProvider provider);
        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.TestConnection(provider, ct));
    }
}
