// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.ContentTemplateController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.ContentTemplate;
using Fakvio.Domain.Enums;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping ContentTemplateController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class ContentTemplateFunctions
{
    private readonly ContentTemplateController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public ContentTemplateFunctions(ContentTemplateController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/contenttemplate → ContentTemplateController.GetAll
    /// </summary>
    [Function("ContentTemplate_GetAll")]
    public async Task<IActionResult> ContentTemplate_GetAll(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/contenttemplate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse nullable enum from query: ?templateType=Value
        global::Fakvio.Domain.Enums.EContentTemplateType? templateType = req.Query.TryGetValue("templateType", out var _templateTypeVal) && Enum.TryParse(_templateTypeVal.ToString(), true, out global::Fakvio.Domain.Enums.EContentTemplateType _templateTypeParsed)
            ? _templateTypeParsed
            : null;
        bool.TryParse(req.Query["includeInactive"], out var includeInactive);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetAll(templateType, includeInactive, cancellationToken));
    }

    /// <summary>
    /// GET api/contenttemplate/{id} → ContentTemplateController.GetById
    /// </summary>
    [Function("ContentTemplate_GetById")]
    public async Task<IActionResult> ContentTemplate_GetById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/contenttemplate/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetById(id, cancellationToken));
    }

    /// <summary>
    /// GET api/contenttemplate/default/{templateType} → ContentTemplateController.GetDefaultByType
    /// </summary>
    [Function("ContentTemplate_GetDefaultByType")]
    public async Task<IActionResult> ContentTemplate_GetDefaultByType(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/contenttemplate/default/{templateType}")] HttpRequest req,
        global::Fakvio.Domain.Enums.EContentTemplateType templateType)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetDefaultByType(templateType, cancellationToken));
    }

    /// <summary>
    /// POST api/contenttemplate → ContentTemplateController.Create
    /// </summary>
    [Function("ContentTemplate_Create")]
    public async Task<IActionResult> ContentTemplate_Create(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/contenttemplate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → CreateContentTemplateDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.ContentTemplate.CreateContentTemplateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.Create(createDto!, cancellationToken));
    }

    /// <summary>
    /// PUT api/contenttemplate/{id} → ContentTemplateController.Update
    /// </summary>
    [Function("ContentTemplate_Update")]
    public async Task<IActionResult> ContentTemplate_Update(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/contenttemplate/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → UpdateContentTemplateDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.ContentTemplate.UpdateContentTemplateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.Update(id, updateDto!, cancellationToken));
    }

    /// <summary>
    /// DELETE api/contenttemplate/{id} → ContentTemplateController.Delete
    /// </summary>
    [Function("ContentTemplate_Delete")]
    public async Task<IActionResult> ContentTemplate_Delete(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/contenttemplate/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.Delete(id, cancellationToken));
    }
}
