// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.CurrencyController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.Currency;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping CurrencyController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class CurrencyFunctions
{
    private readonly CurrencyController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public CurrencyFunctions(CurrencyController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/currency/active → CurrencyController.GetActiveCurrencies
    /// </summary>
    [Function("Currency_GetActiveCurrencies")]
    public async Task<IActionResult> Currency_GetActiveCurrencies(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/currency/active")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetActiveCurrencies(cancellationToken));
    }

    /// <summary>
    /// GET api/currency → CurrencyController.GetCurrenciesPaged
    /// </summary>
    [Function("Currency_GetCurrenciesPaged")]
    public async Task<IActionResult> Currency_GetCurrenciesPaged(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/currency")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [SysAdmin]
        if (!req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        int.TryParse(req.Query["page"], out var page);
        if (!req.Query.ContainsKey("page")) page = 1;
        int.TryParse(req.Query["pageSize"], out var pageSize);
        if (!req.Query.ContainsKey("pageSize")) pageSize = 10;
        string? search = req.Query.TryGetValue("search", out var _searchVal) ? _searchVal.ToString() : null;
        bool? isActive = bool.TryParse(req.Query["isActive"], out var _isActiveParsed) ? _isActiveParsed : null;
        string sortBy = req.Query["sortBy"].ToString() ?? "SortOrder";
        bool.TryParse(req.Query["isDescending"], out var isDescending);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetCurrenciesPaged(page, pageSize, search, isActive, sortBy, isDescending, cancellationToken));
    }

    /// <summary>
    /// GET api/currency/{id} → CurrencyController.GetCurrencyById
    /// </summary>
    [Function("Currency_GetCurrencyById")]
    public async Task<IActionResult> Currency_GetCurrencyById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/currency/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetCurrencyById(id, cancellationToken));
    }

    /// <summary>
    /// POST api/currency → CurrencyController.CreateCurrency
    /// </summary>
    [Function("Currency_CreateCurrency")]
    public async Task<IActionResult> Currency_CreateCurrency(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/currency")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [SysAdmin]
        if (!req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → CreateCurrencyDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.Currency.CreateCurrencyDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateCurrency(createDto!, cancellationToken));
    }

    /// <summary>
    /// PUT api/currency/{id} → CurrencyController.UpdateCurrency
    /// </summary>
    [Function("Currency_UpdateCurrency")]
    public async Task<IActionResult> Currency_UpdateCurrency(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/currency/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [SysAdmin]
        if (!req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → UpdateCurrencyDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.Currency.UpdateCurrencyDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.UpdateCurrency(id, updateDto!, cancellationToken));
    }

    /// <summary>
    /// DELETE api/currency/{id} → CurrencyController.DeleteCurrency
    /// </summary>
    [Function("Currency_DeleteCurrency")]
    public async Task<IActionResult> Currency_DeleteCurrency(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/currency/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [SysAdmin]
        if (!req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.DeleteCurrency(id, cancellationToken));
    }
}
