// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.DashboardController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping DashboardController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class DashboardFunctions
{
    private readonly DashboardController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public DashboardFunctions(DashboardController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/dashboard → DashboardController.GetDashboard
    /// </summary>
    [Function("Dashboard_GetDashboard")]
    public async Task<IActionResult> Dashboard_GetDashboard(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/dashboard")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetDashboard(cancellationToken));
    }

    /// <summary>
    /// GET api/dashboard/sysadmin → DashboardController.GetSysAdminDashboard
    /// </summary>
    [Function("Dashboard_GetSysAdminDashboard")]
    public async Task<IActionResult> Dashboard_GetSysAdminDashboard(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/dashboard/sysadmin")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [SysAdmin]
        if (!req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var ct = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetSysAdminDashboard(ct));
    }
}
