// <auto-generated/>
// Source controller: Fakvio.API.Controller.EmailController

#nullable enable

using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.Email;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Azure Functions HTTP trigger wrapping EmailController.
/// SysAdmin-only endpoint for sending custom emails via system SMTP.
/// </summary>
public class EmailFunctions
{
    private readonly EmailController _controller;

    public EmailFunctions(EmailController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// POST api/email/send → EmailController.SendEmail
    /// Requires SysAdmin role.
    /// </summary>
    [Function("Email_Send")]
    public async Task<IActionResult> Email_Send(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/email/send")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check — SysAdmin only.
        var role = req.HttpContext.User.FindFirst(ClaimTypes.Role)?.Value;
        if (role != "SysAdmin")
            return new ForbidResult();

        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<SendEmailDto>(
            req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        return FunctionResultHelper.Normalize(
            await _controller.SendEmail(dto!, req.HttpContext.RequestAborted));
    }
}
