// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.InvoiceTemplateController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.InvoiceTemplate;
using Fakvio.Domain.Enums;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping InvoiceTemplateController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class InvoiceTemplateFunctions
{
    private readonly InvoiceTemplateController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public InvoiceTemplateFunctions(InvoiceTemplateController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/invoicetemplate/active → InvoiceTemplateController.GetActiveTemplates
    /// </summary>
    [Function("InvoiceTemplate_GetActiveTemplates")]
    public async Task<IActionResult> InvoiceTemplate_GetActiveTemplates(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/invoicetemplate/active")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse nullable enum from query: ?documentType=Value
        global::Fakvio.Domain.Enums.EDocumentType? documentType = req.Query.TryGetValue("documentType", out var _documentTypeVal) && Enum.TryParse(_documentTypeVal.ToString(), true, out global::Fakvio.Domain.Enums.EDocumentType _documentTypeParsed)
            ? _documentTypeParsed
            : null;
        string? category = req.Query.TryGetValue("category", out var _categoryVal) ? _categoryVal.ToString() : null;
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetActiveTemplates(documentType, category, cancellationToken));
    }

    /// <summary>
    /// GET api/invoicetemplate → InvoiceTemplateController.GetTemplatesPaged
    /// </summary>
    [Function("InvoiceTemplate_GetTemplatesPaged")]
    public async Task<IActionResult> InvoiceTemplate_GetTemplatesPaged(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/invoicetemplate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        int.TryParse(req.Query["page"], out var page);
        if (!req.Query.ContainsKey("page")) page = 1;
        int.TryParse(req.Query["pageSize"], out var pageSize);
        if (!req.Query.ContainsKey("pageSize")) pageSize = 10;
        string? search = req.Query.TryGetValue("search", out var _searchVal) ? _searchVal.ToString() : null;
        string? name = req.Query.TryGetValue("name", out var _nameVal) ? _nameVal.ToString() : null;
        // Parse nullable enum from query: ?documentType=Value
        global::Fakvio.Domain.Enums.EDocumentType? documentType = req.Query.TryGetValue("documentType", out var _documentTypeVal) && Enum.TryParse(_documentTypeVal.ToString(), true, out global::Fakvio.Domain.Enums.EDocumentType _documentTypeParsed)
            ? _documentTypeParsed
            : null;
        string? category = req.Query.TryGetValue("category", out var _categoryVal) ? _categoryVal.ToString() : null;
        bool? isActive = bool.TryParse(req.Query["isActive"], out var _isActiveParsed) ? _isActiveParsed : null;
        long? issuerId = long.TryParse(req.Query["issuerId"], out var _issuerIdParsed) ? _issuerIdParsed : null;
        string sortBy = req.Query["sortBy"].ToString() ?? "Name";
        bool.TryParse(req.Query["isDescending"], out var isDescending);
        DateTime? lastUsedAtFrom = DateTime.TryParse(req.Query["lastUsedAtFrom"], out var _lastUsedFromParsed) ? _lastUsedFromParsed : null;
        DateTime? lastUsedAtTo = DateTime.TryParse(req.Query["lastUsedAtTo"], out var _lastUsedToParsed) ? _lastUsedToParsed : null;
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetTemplatesPaged(
            page, pageSize, search, name, documentType, category, isActive, issuerId, sortBy, isDescending,
            lastUsedAtFrom, lastUsedAtTo, cancellationToken));
    }

    /// <summary>
    /// GET api/invoicetemplate/{id} → InvoiceTemplateController.GetTemplateById
    /// </summary>
    [Function("InvoiceTemplate_GetTemplateById")]
    public async Task<IActionResult> InvoiceTemplate_GetTemplateById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/invoicetemplate/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetTemplateById(__id_parsed, cancellationToken));
    }

    /// <summary>
    /// POST api/invoicetemplate → InvoiceTemplateController.CreateTemplate
    /// </summary>
    [Function("InvoiceTemplate_CreateTemplate")]
    public async Task<IActionResult> InvoiceTemplate_CreateTemplate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/invoicetemplate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Deserialize request body → CreateInvoiceTemplateDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.InvoiceTemplate.CreateInvoiceTemplateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateTemplate(createDto!, cancellationToken));
    }

    /// <summary>
    /// PUT api/invoicetemplate/{id} → InvoiceTemplateController.UpdateTemplate
    /// </summary>
    [Function("InvoiceTemplate_UpdateTemplate")]
    public async Task<IActionResult> InvoiceTemplate_UpdateTemplate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/invoicetemplate/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Deserialize request body → UpdateInvoiceTemplateDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.InvoiceTemplate.UpdateInvoiceTemplateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.UpdateTemplate(__id_parsed, updateDto!, cancellationToken));
    }

    /// <summary>
    /// DELETE api/invoicetemplate/{id} → InvoiceTemplateController.DeleteTemplate
    /// </summary>
    [Function("InvoiceTemplate_DeleteTemplate")]
    public async Task<IActionResult> InvoiceTemplate_DeleteTemplate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/invoicetemplate/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.DeleteTemplate(__id_parsed, cancellationToken));
    }

    /// <summary>
    /// POST api/invoicetemplate/{id:long}/create-invoice → InvoiceTemplateController.CreateInvoiceFromTemplate
    /// </summary>
    [Function("InvoiceTemplate_CreateInvoiceFromTemplate")]
    public async Task<IActionResult> InvoiceTemplate_CreateInvoiceFromTemplate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/invoicetemplate/{id:long}/create-invoice")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Deserialize request body → CreateInvoiceFromTemplateDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.InvoiceTemplate.CreateInvoiceFromTemplateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateInvoiceFromTemplate(__id_parsed, createDto!, cancellationToken));
    }

    /// <summary>
    /// POST api/invoicetemplate/from-invoice/{invoiceId} → InvoiceTemplateController.CreateTemplateFromInvoice
    /// </summary>
    [Function("InvoiceTemplate_CreateTemplateFromInvoice")]
    public async Task<IActionResult> InvoiceTemplate_CreateTemplateFromInvoice(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/invoicetemplate/from-invoice/{invoiceId:long}")] HttpRequest req,
        string invoiceId)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(invoiceId, out var __invoiceId_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'invoiceId'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Deserialize request body → CreateTemplateFromInvoiceRequest
        var request = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.API.Controller.InvoiceTemplateController.CreateTemplateFromInvoiceRequest>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateTemplateFromInvoice(__invoiceId_parsed, request!, cancellationToken));
    }
}
