// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.NumberSequenceController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.NumberSequence;
using Fakvio.Domain.Enums;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping NumberSequenceController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class NumberSequenceFunctions
{
    private readonly NumberSequenceController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public NumberSequenceFunctions(NumberSequenceController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/numbersequence/formats → NumberSequenceController.GetAllFormats
    /// </summary>
    [Function("NumberSequence_GetAllFormats")]
    public async Task<IActionResult> NumberSequence_GetAllFormats(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/formats")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        bool.TryParse(req.Query["includeInactive"], out var includeInactive);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetAllFormats(includeInactive, cancellationToken));
    }

    /// <summary>
    /// GET api/numbersequence/formats/{id} → NumberSequenceController.GetFormatById
    /// </summary>
    [Function("NumberSequence_GetFormatById")]
    public async Task<IActionResult> NumberSequence_GetFormatById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/formats/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetFormatById(id, cancellationToken));
    }

    /// <summary>
    /// POST api/numbersequence/formats → NumberSequenceController.CreateFormat
    /// </summary>
    [Function("NumberSequence_CreateFormat")]
    public async Task<IActionResult> NumberSequence_CreateFormat(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/numbersequence/formats")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → CreateNumberSequenceFormatDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.NumberSequence.CreateNumberSequenceFormatDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateFormat(createDto!, cancellationToken));
    }

    /// <summary>
    /// PUT api/numbersequence/formats/{id} → NumberSequenceController.UpdateFormat
    /// </summary>
    [Function("NumberSequence_UpdateFormat")]
    public async Task<IActionResult> NumberSequence_UpdateFormat(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/numbersequence/formats/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → UpdateNumberSequenceFormatDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.NumberSequence.UpdateNumberSequenceFormatDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.UpdateFormat(id, updateDto!, cancellationToken));
    }

    /// <summary>
    /// GET api/numbersequence/formats/validate → NumberSequenceController.ValidateFormatPattern
    /// </summary>
    [Function("NumberSequence_ValidateFormatPattern")]
    public IActionResult NumberSequence_ValidateFormatPattern(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/formats/validate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        string pattern = req.Query["pattern"].ToString() ?? "";

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(_controller.ValidateFormatPattern(pattern));
    }

    /// <summary>
    /// GET api/numbersequence → NumberSequenceController.GetAllSequences
    /// </summary>
    [Function("NumberSequence_GetAllSequences")]
    public async Task<IActionResult> NumberSequence_GetAllSequences(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse nullable enum from query: ?documentType=Value
        global::Fakvio.Domain.Enums.EDocumentType? documentType = req.Query.TryGetValue("documentType", out var _documentTypeVal) && Enum.TryParse(_documentTypeVal.ToString(), true, out global::Fakvio.Domain.Enums.EDocumentType _documentTypeParsed)
            ? _documentTypeParsed
            : null;
        bool.TryParse(req.Query["includeInactive"], out var includeInactive);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetAllSequences(documentType, includeInactive, cancellationToken));
    }

    /// <summary>
    /// GET api/numbersequence/{id} → NumberSequenceController.GetSequenceById
    /// </summary>
    [Function("NumberSequence_GetSequenceById")]
    public async Task<IActionResult> NumberSequence_GetSequenceById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetSequenceById(id, cancellationToken));
    }

    /// <summary>
    /// GET api/numbersequence/default/{documentType} → NumberSequenceController.GetDefaultSequence
    /// </summary>
    [Function("NumberSequence_GetDefaultSequence")]
    public async Task<IActionResult> NumberSequence_GetDefaultSequence(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/default/{documentType}")] HttpRequest req,
        global::Fakvio.Domain.Enums.EDocumentType documentType)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetDefaultSequence(documentType, cancellationToken));
    }

    /// <summary>
    /// POST api/numbersequence → NumberSequenceController.CreateSequence
    /// </summary>
    [Function("NumberSequence_CreateSequence")]
    public async Task<IActionResult> NumberSequence_CreateSequence(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/numbersequence")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → CreateNumberSequenceDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.NumberSequence.CreateNumberSequenceDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateSequence(createDto!, cancellationToken));
    }

    /// <summary>
    /// PUT api/numbersequence/{id} → NumberSequenceController.UpdateSequence
    /// </summary>
    [Function("NumberSequence_UpdateSequence")]
    public async Task<IActionResult> NumberSequence_UpdateSequence(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/numbersequence/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → UpdateNumberSequenceDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.NumberSequence.UpdateNumberSequenceDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.UpdateSequence(id, updateDto!, cancellationToken));
    }

    /// <summary>
    /// POST api/numbersequence/{id}/set-default → NumberSequenceController.SetAsDefault
    /// </summary>
    [Function("NumberSequence_SetAsDefault")]
    public async Task<IActionResult> NumberSequence_SetAsDefault(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/numbersequence/{id}/set-default")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.SetAsDefault(id, cancellationToken));
    }

    /// <summary>
    /// DELETE api/numbersequence/{id} → NumberSequenceController.DeactivateSequence
    /// </summary>
    [Function("NumberSequence_DeactivateSequence")]
    public async Task<IActionResult> NumberSequence_DeactivateSequence(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/numbersequence/{id}")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.DeactivateSequence(id, cancellationToken));
    }

    /// <summary>
    /// GET api/numbersequence/{id}/preview → NumberSequenceController.PreviewNextNumber
    /// </summary>
    [Function("NumberSequence_PreviewNextNumber")]
    public async Task<IActionResult> NumberSequence_PreviewNextNumber(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/{id}/preview")] HttpRequest req,
        long id)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        DateTime? issueDate = DateTime.TryParse(req.Query["issueDate"], out var _issueDateParsed) ? _issueDateParsed : null;
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.PreviewNextNumber(id, issueDate, cancellationToken));
    }

    /// <summary>
    /// GET api/numbersequence/preview-by-type → NumberSequenceController.PreviewByDocumentType
    /// </summary>
    [Function("NumberSequence_PreviewByDocumentType")]
    public async Task<IActionResult> NumberSequence_PreviewByDocumentType(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/numbersequence/preview-by-type")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse enum from query: ?documentType=Value
        Enum.TryParse(req.Query["documentType"].ToString(), true, out global::Fakvio.Domain.Enums.EDocumentType documentType);
        DateTime? issueDate = DateTime.TryParse(req.Query["issueDate"], out var _issueDateParsed) ? _issueDateParsed : null;
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.PreviewByDocumentType(documentType, issueDate, cancellationToken));
    }
}
