// <auto-generated/>
// This file was created manually following the pattern of the auto-generated wrappers
// produced by Fakvio.Functions.Generator. Source controller:
// Fakvio.API.Controller.PaymentMatchingController
//
// Why this exists separately from /PaymentMatchingFunctions.cs (timer trigger):
// The repo has TWO classes called PaymentMatchingFunctions in two different namespaces:
//   1. Fakvio.Functions.PaymentMatchingFunctions     — timer trigger ([TimerTrigger])
//   2. Fakvio.Functions.Generated.PaymentMatchingFunctions — HTTP triggers (THIS file)
// Same short class name is fine because the namespaces differ. To avoid Azure Functions
// "duplicate function name" errors at startup, every [Function("...")] attribute below
// uses the "PaymentMatching_*" prefix that mirrors the auto-generator's naming scheme.
//
// Bug fixed: GitHub issue #6 — /payments page returned HTTP 404 from the Functions host
// because PaymentMatching* HTTP wrappers were missing. See CLAUDE.md
// § "API + Functions duplication" for the rule this implements.

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.PaymentMatching;
using Fakvio.Domain.Enums;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Azure Functions HTTP triggers wrapping <see cref="PaymentMatchingController"/>.
/// Each public action method on the controller is exposed as a separate Azure Function
/// with the same route (api/payment-matching/*).
///
/// Why this file exists: Azure Functions doesn't auto-discover MVC controller routes,
/// so every controller needs a thin wrapper that:
///   1. pins the HTTP trigger route,
///   2. enforces the [Authorize] check manually (Functions Isolated Worker doesn't
///      run UseAuthentication/UseAuthorization automatically),
///   3. parses route + query + body parameters,
///   4. invokes the controller action and normalizes the result.
///
/// The controller is resolved from DI thanks to AddControllersAsServices() in Program.cs.
/// </summary>
public class PaymentMatchingFunctions
{
    private readonly PaymentMatchingController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public PaymentMatchingFunctions(PaymentMatchingController controller)
    {
        _controller = controller;
    }

    // ─── Mailbox lifecycle ──────────────────────────────────────────────────

    /// <summary>
    /// GET api/payment-matching/mailbox/{bankAccountId}
    /// → <see cref="PaymentMatchingController.GetMailbox"/>
    /// </summary>
    [Function("PaymentMatching_GetMailbox")]
    public async Task<IActionResult> PaymentMatching_GetMailbox(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/payment-matching/mailbox/{bankAccountId:long}")] HttpRequest req,
        string bankAccountId)
    {
        // Azure Functions can't bind "long" route parameters directly; we receive it as
        // string and parse it manually. Same approach used by the auto-generated wrappers.
        if (!long.TryParse(bankAccountId, out var bankAccountIdParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'bankAccountId'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // [Authorize] enforcement — JwtAuthenticationMiddleware populates HttpContext.User.
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.GetMailbox(bankAccountIdParsed, ct));
    }

    /// <summary>
    /// POST api/payment-matching/mailbox/{bankAccountId}/activate
    /// → <see cref="PaymentMatchingController.ActivateMailbox"/>
    /// </summary>
    [Function("PaymentMatching_ActivateMailbox")]
    public async Task<IActionResult> PaymentMatching_ActivateMailbox(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/mailbox/{bankAccountId:long}/activate")] HttpRequest req,
        string bankAccountId)
    {
        if (!long.TryParse(bankAccountId, out var bankAccountIdParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'bankAccountId'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.ActivateMailbox(bankAccountIdParsed, ct));
    }

    /// <summary>
    /// POST api/payment-matching/mailbox/{bankAccountId}/deactivate
    /// → <see cref="PaymentMatchingController.DeactivateMailbox"/>
    /// </summary>
    [Function("PaymentMatching_DeactivateMailbox")]
    public async Task<IActionResult> PaymentMatching_DeactivateMailbox(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/mailbox/{bankAccountId:long}/deactivate")] HttpRequest req,
        string bankAccountId)
    {
        if (!long.TryParse(bankAccountId, out var bankAccountIdParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'bankAccountId'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.DeactivateMailbox(bankAccountIdParsed, ct));
    }

    /// <summary>
    /// POST api/payment-matching/mailbox/{bankAccountId}/regenerate
    /// → <see cref="PaymentMatchingController.RegenerateMailbox"/>
    /// </summary>
    [Function("PaymentMatching_RegenerateMailbox")]
    public async Task<IActionResult> PaymentMatching_RegenerateMailbox(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/mailbox/{bankAccountId:long}/regenerate")] HttpRequest req,
        string bankAccountId)
    {
        if (!long.TryParse(bankAccountId, out var bankAccountIdParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'bankAccountId'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.RegenerateMailbox(bankAccountIdParsed, ct));
    }

    // ─── Bank transactions grid ─────────────────────────────────────────────

    /// <summary>
    /// GET api/payment-matching/transactions
    /// → <see cref="PaymentMatchingController.ListTransactions"/>
    ///
    /// Query string parameters:
    ///   status (EMatchStatus?), direction (EPaymentDirection?), bankAccountId (long?),
    ///   from (DateTime?), to (DateTime?), search (string?),
    ///   page (int, default 1), pageSize (int, default 50)
    /// </summary>
    [Function("PaymentMatching_ListTransactions")]
    public async Task<IActionResult> PaymentMatching_ListTransactions(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/payment-matching/transactions")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Parse all filter inputs from query string. Functions can't auto-bind
        // [FromQuery] enum/nullable parameters, so we do it by hand. Same style
        // as the auto-generated InvoiceFunctions.GetAllInvoices.
        EMatchStatus? status = req.Query.TryGetValue("status", out var statusRaw)
                               && Enum.TryParse<EMatchStatus>(statusRaw.ToString(), ignoreCase: true, out var statusParsed)
            ? statusParsed
            : null;

        EPaymentDirection? direction = req.Query.TryGetValue("direction", out var directionRaw)
                                       && Enum.TryParse<EPaymentDirection>(directionRaw.ToString(), ignoreCase: true, out var directionParsed)
            ? directionParsed
            : null;

        long? bankAccountId = long.TryParse(req.Query["bankAccountId"], out var bankAccountIdParsed)
            ? bankAccountIdParsed
            : null;

        DateTime? from = DateTime.TryParse(req.Query["from"], out var fromParsed) ? fromParsed : null;
        DateTime? to = DateTime.TryParse(req.Query["to"], out var toParsed) ? toParsed : null;

        string? search = req.Query.TryGetValue("search", out var searchRaw) ? searchRaw.ToString() : null;

        int page = int.TryParse(req.Query["page"], out var pageParsed) ? pageParsed : 1;
        int pageSize = int.TryParse(req.Query["pageSize"], out var pageSizeParsed) ? pageSizeParsed : 50;

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(
            await _controller.ListTransactions(status, direction, bankAccountId, from, to, search, page, pageSize, ct));
    }

    /// <summary>
    /// GET api/payment-matching/transactions/{id}
    /// → <see cref="PaymentMatchingController.GetTransaction"/>
    /// </summary>
    [Function("PaymentMatching_GetTransaction")]
    public async Task<IActionResult> PaymentMatching_GetTransaction(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/payment-matching/transactions/{id:long}")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.GetTransaction(idParsed, ct));
    }

    /// <summary>
    /// POST api/payment-matching/transactions/{id}/match
    /// → <see cref="PaymentMatchingController.Match"/>
    /// Request body: <see cref="ManualMatchRequest"/>.
    /// </summary>
    [Function("PaymentMatching_Match")]
    public async Task<IActionResult> PaymentMatching_Match(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/transactions/{id:long}/match")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        // Body is the manual-match payload from the UI dialog.
        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<ManualMatchRequest>(
            req.Body, FunctionResultHelper.JsonOptions, ct);

        if (dto == null)
            return new BadRequestObjectResult(new { message = "Invalid request body." });

        return FunctionResultHelper.Normalize(await _controller.Match(idParsed, dto, ct));
    }

    /// <summary>
    /// POST api/payment-matching/transactions/{id}/unmatch
    /// → <see cref="PaymentMatchingController.Unmatch"/>
    /// Request body: <see cref="UnmatchRequest"/>.
    /// </summary>
    [Function("PaymentMatching_Unmatch")]
    public async Task<IActionResult> PaymentMatching_Unmatch(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/transactions/{id:long}/unmatch")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<UnmatchRequest>(
            req.Body, FunctionResultHelper.JsonOptions, ct);

        if (dto == null)
            return new BadRequestObjectResult(new { message = "Invalid request body." });

        return FunctionResultHelper.Normalize(await _controller.Unmatch(idParsed, dto, ct));
    }

    /// <summary>
    /// POST api/payment-matching/transactions/{id}/ignore
    /// → <see cref="PaymentMatchingController.Ignore"/>
    /// </summary>
    [Function("PaymentMatching_Ignore")]
    public async Task<IActionResult> PaymentMatching_Ignore(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/transactions/{id:long}/ignore")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.Ignore(idParsed, ct));
    }

    // ─── Dashboard ──────────────────────────────────────────────────────────

    /// <summary>
    /// GET api/payment-matching/unmatched-count
    /// → <see cref="PaymentMatchingController.UnmatchedCount"/>
    /// Used by the navbar badge to indicate transactions that need user attention.
    /// </summary>
    [Function("PaymentMatching_UnmatchedCount")]
    public async Task<IActionResult> PaymentMatching_UnmatchedCount(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/payment-matching/unmatched-count")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.UnmatchedCount(ct));
    }

    // ─── Auto-match ─────────────────────────────────────────────────────────

    /// <summary>
    /// POST api/payment-matching/transactions/{id}/auto-match
    /// → <see cref="PaymentMatchingController.FindAutoMatchForTransaction"/>
    /// Searches for an invoice matching this unmatched bank transaction by VS or amount.
    /// </summary>
    [Function("PaymentMatching_FindAutoMatchForTransaction")]
    public async Task<IActionResult> PaymentMatching_FindAutoMatchForTransaction(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/transactions/{id:long}/auto-match")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.FindAutoMatchForTransaction(idParsed, ct));
    }

    /// <summary>
    /// POST api/payment-matching/confirm-auto-match
    /// → <see cref="PaymentMatchingController.ConfirmAutoMatch"/>
    /// Body: <see cref="ConfirmAutoMatchRequest"/> with BankTransactionId +
    /// either InvoiceId or ReceivedInvoiceId.
    /// Creates the PaymentMatch row and updates the invoice status.
    /// </summary>
    [Function("PaymentMatching_ConfirmAutoMatch")]
    public async Task<IActionResult> PaymentMatching_ConfirmAutoMatch(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/confirm-auto-match")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        // Deserialize the auto-match confirmation payload.
        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<ConfirmAutoMatchRequest>(
            req.Body, FunctionResultHelper.JsonOptions, ct);

        if (dto == null)
            return new BadRequestObjectResult(new { message = "Invalid request body." });

        return FunctionResultHelper.Normalize(await _controller.ConfirmAutoMatch(dto, ct));
    }

    /// <summary>
    /// POST api/payment-matching/transactions/{id}/assign-recognized
    /// → <see cref="PaymentMatchingController.AssignRecognized"/>
    /// Request body: <see cref="Fakvio.Contracts.Dto.RecognizedCounterparty.AssignRecognizedRequest"/>.
    /// </summary>
    [Function("PaymentMatching_AssignRecognized")]
    public async Task<IActionResult> PaymentMatching_AssignRecognized(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/transactions/{id:long}/assign-recognized")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<Fakvio.Contracts.Dto.RecognizedCounterparty.AssignRecognizedRequest>(
            req.Body, FunctionResultHelper.JsonOptions, ct);

        if (dto == null)
            return new BadRequestObjectResult(new { message = "Invalid request body." });

        return FunctionResultHelper.Normalize(await _controller.AssignRecognized(idParsed, dto, ct));
    }

    /// <summary>
    /// POST api/payment-matching/transactions/{id}/unassign-recognized
    /// → <see cref="PaymentMatchingController.UnassignRecognized"/>
    /// </summary>
    [Function("PaymentMatching_UnassignRecognized")]
    public async Task<IActionResult> PaymentMatching_UnassignRecognized(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/payment-matching/transactions/{id:long}/unassign-recognized")] HttpRequest req,
        string id)
    {
        if (!long.TryParse(id, out var idParsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.UnassignRecognized(idParsed, ct));
    }
}
