// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.ReadinessController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping ReadinessController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class ReadinessFunctions
{
    private readonly ReadinessController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public ReadinessFunctions(ReadinessController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/readiness → ReadinessController.GetReport
    /// </summary>
    [Function("Readiness_GetReport")]
    public async Task<IActionResult> Readiness_GetReport(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/readiness")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        long? issuerId = long.TryParse(req.Query["issuerId"], out var _issuerIdParsed) ? _issuerIdParsed : null;
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetReport(issuerId, cancellationToken));
    }
}
