// <auto-generated/>
// This file was created manually to match the pattern of auto-generated Functions.
// Source controller: Fakvio.API.Controller.ReceivedInvoiceController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.ReceivedInvoice;
using Fakvio.Domain.Enums;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Azure Functions HTTP triggers wrapping ReceivedInvoiceController.
/// Exposes all received invoice CRUD and status transition endpoints.
/// </summary>
public class ReceivedInvoiceFunctions
{
    private readonly ReceivedInvoiceController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public ReceivedInvoiceFunctions(ReceivedInvoiceController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/received-invoice → ReceivedInvoiceController.GetAll
    /// </summary>
    [Function("ReceivedInvoice_GetAll")]
    public async Task<IActionResult> ReceivedInvoice_GetAll(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/received-invoice")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        // Parse optional query parameters
        EReceivedInvoiceStatus? status = Enum.TryParse<EReceivedInvoiceStatus>(req.Query["status"], out var s) ? s : null;
        long? supplierId = long.TryParse(req.Query["supplierId"], out var sid) ? sid : null;

        return FunctionResultHelper.Normalize(await _controller.GetAll(status, supplierId, ct));
    }

    /// <summary>
    /// GET api/received-invoice/paged → ReceivedInvoiceController.GetPaged
    /// </summary>
    [Function("ReceivedInvoice_GetPaged")]
    public async Task<IActionResult> ReceivedInvoice_GetPaged(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/received-invoice/paged")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;

        // Model binding: ASP.NET MVC auto-binds [FromQuery] on the controller,
        // but Azure Functions doesn't. Parse filter from query string manually.
        var filter = new ReceivedInvoiceFilterDto
        {
            Page = int.TryParse(req.Query["page"], out var p) ? p : 1,
            PageSize = int.TryParse(req.Query["pageSize"], out var ps) ? ps : 20,
            Search = req.Query["search"],
            Status = Enum.TryParse<EReceivedInvoiceStatus>(req.Query["status"], out var st) ? st : null,
            SupplierId = long.TryParse(req.Query["supplierId"], out var sup) ? sup : null
        };

        return FunctionResultHelper.Normalize(await _controller.GetPaged(filter, ct));
    }

    /// <summary>
    /// GET api/received-invoice/{id} → ReceivedInvoiceController.GetById
    /// </summary>
    [Function("ReceivedInvoice_GetById")]
    public async Task<IActionResult> ReceivedInvoice_GetById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/received-invoice/{id:long}")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.GetById(id, ct));
    }

    /// <summary>
    /// POST api/received-invoice → ReceivedInvoiceController.Create
    /// </summary>
    [Function("ReceivedInvoice_Create")]
    public async Task<IActionResult> ReceivedInvoice_Create(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/received-invoice")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<CreateReceivedInvoiceDto>(
            req.Body, FunctionResultHelper.JsonOptions, ct);

        if (dto == null)
            return new BadRequestObjectResult(new { message = "Invalid request body." });

        return FunctionResultHelper.Normalize(await _controller.Create(dto, ct));
    }

    /// <summary>
    /// PUT api/received-invoice/{id} → ReceivedInvoiceController.Update
    /// </summary>
    [Function("ReceivedInvoice_Update")]
    public async Task<IActionResult> ReceivedInvoice_Update(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/received-invoice/{id:long}")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<UpdateReceivedInvoiceDto>(
            req.Body, FunctionResultHelper.JsonOptions, ct);

        if (dto == null)
            return new BadRequestObjectResult(new { message = "Invalid request body." });

        return FunctionResultHelper.Normalize(await _controller.Update(id, dto, ct));
    }

    /// <summary>
    /// POST api/received-invoice/{id}/approve → ReceivedInvoiceController.Approve
    /// </summary>
    [Function("ReceivedInvoice_Approve")]
    public async Task<IActionResult> ReceivedInvoice_Approve(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/received-invoice/{id:long}/approve")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.Approve(id, ct));
    }

    /// <summary>
    /// POST api/received-invoice/{id}/mark-paid → ReceivedInvoiceController.MarkAsPaid
    /// </summary>
    [Function("ReceivedInvoice_MarkAsPaid")]
    public async Task<IActionResult> ReceivedInvoice_MarkAsPaid(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/received-invoice/{id:long}/mark-paid")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        DateTime? paidAt = DateTime.TryParse(req.Query["paidAt"], out var pa) ? pa : null;

        return FunctionResultHelper.Normalize(await _controller.MarkAsPaid(id, paidAt, ct));
    }

    /// <summary>
    /// POST api/received-invoice/{id}/reject → ReceivedInvoiceController.Reject
    /// </summary>
    [Function("ReceivedInvoice_Reject")]
    public async Task<IActionResult> ReceivedInvoice_Reject(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/received-invoice/{id:long}/reject")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.Reject(id, ct));
    }

    /// <summary>
    /// DELETE api/received-invoice/{id} → ReceivedInvoiceController.Delete
    /// </summary>
    [Function("ReceivedInvoice_Delete")]
    public async Task<IActionResult> ReceivedInvoice_Delete(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/received-invoice/{id:long}")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.Delete(id, ct));
    }

    // ─── Payment matching ─────────────────────────────────────────────────────

    /// <summary>
    /// GET api/received-invoice/{id}/payments → ReceivedInvoiceController.GetPayments
    /// Returns all PaymentMatch rows linked to the received invoice.
    /// </summary>
    [Function("ReceivedInvoice_GetPayments")]
    public async Task<IActionResult> ReceivedInvoice_GetPayments(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/received-invoice/{id:long}/payments")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.GetPayments(id, ct));
    }

    /// <summary>
    /// POST api/received-invoice/{id}/auto-match → ReceivedInvoiceController.FindAutoMatch
    /// Searches for an unmatched bank transaction that matches the received invoice.
    /// Returns the best proposal or 204 NoContent when nothing found.
    /// </summary>
    [Function("ReceivedInvoice_FindAutoMatch")]
    public async Task<IActionResult> ReceivedInvoice_FindAutoMatch(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/received-invoice/{id:long}/auto-match")] HttpRequest req,
        long id)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var ct = req.HttpContext.RequestAborted;
        return FunctionResultHelper.Normalize(await _controller.FindAutoMatch(id, ct));
    }
}
