// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.UserController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.User;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping UserController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class UserFunctions
{
    private readonly UserController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public UserFunctions(UserController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/user → UserController.GetAllUsers
    /// </summary>
    [Function("User_GetAllUsers")]
    public async Task<IActionResult> User_GetAllUsers(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/user")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        long? companyId = long.TryParse(req.Query["companyId"], out var _companyIdParsed) ? _companyIdParsed : null;
        bool.TryParse(req.Query["includeInactive"], out var includeInactive);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetAllUsers(companyId, includeInactive));
    }

    /// <summary>
    /// GET api/user/paged → UserController.GetUsersPaged
    /// </summary>
    [Function("User_GetUsersPaged")]
    public async Task<IActionResult> User_GetUsersPaged(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/user/paged")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Bind complex DTO from query string parameters
        var filter = FunctionResultHelper.BindFromQuery<global::Fakvio.Contracts.Dto.User.UserFilterDto>(req.Query);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetUsersPaged(filter, cancellationToken));
    }

    /// <summary>
    /// GET api/user/{id} → UserController.GetUserById
    /// </summary>
    [Function("User_GetUserById")]
    public async Task<IActionResult> User_GetUserById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/user/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetUserById(__id_parsed));
    }

    /// <summary>
    /// POST api/user → UserController.CreateUser
    /// </summary>
    [Function("User_CreateUser")]
    public async Task<IActionResult> User_CreateUser(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/user")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → CreateUserDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.CreateUserDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateUser(createDto!));
    }

    /// <summary>
    /// PUT api/user/{id} → UserController.UpdateUser
    /// </summary>
    [Function("User_UpdateUser")]
    public async Task<IActionResult> User_UpdateUser(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/user/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → UpdateUserDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.UpdateUserDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.UpdateUser(__id_parsed, updateDto!));
    }

    /// <summary>
    /// POST api/user/{id:long}/change-password → UserController.ChangePassword
    /// </summary>
    [Function("User_ChangePassword")]
    public async Task<IActionResult> User_ChangePassword(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/user/{id:long}/change-password")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Deserialize request body → ChangePasswordDto
        var changePasswordDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.ChangePasswordDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.ChangePassword(__id_parsed, changePasswordDto!));
    }

    /// <summary>
    /// POST api/user/{id:long}/admin-reset-password → UserController.AdminResetPassword
    /// </summary>
    [Function("User_AdminResetPassword")]
    public async Task<IActionResult> User_AdminResetPassword(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/user/{id:long}/admin-reset-password")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → AdminResetPasswordDto
        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.AdminResetPasswordDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.AdminResetPassword(__id_parsed, dto!));
    }

    /// <summary>
    /// DELETE api/user/{id} → UserController.DeleteUser
    /// </summary>
    [Function("User_DeleteUser")]
    public async Task<IActionResult> User_DeleteUser(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/user/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.DeleteUser(__id_parsed));
    }

    /// <summary>
    /// POST api/user/invite → UserController.InviteUser
    /// </summary>
    [Function("User_InviteUser")]
    public async Task<IActionResult> User_InviteUser(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/user/invite")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → InviteUserDto
        var inviteDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.InviteUserDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.InviteUser(inviteDto!));
    }

    /// <summary>
    /// POST api/user/set-password → UserController.SetPassword
    /// </summary>
    [Function("User_SetPassword")]
    public async Task<IActionResult> User_SetPassword(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/user/set-password")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // No authentication required ([AllowAnonymous] or no [Authorize])

        // Deserialize request body → SetPasswordDto
        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.SetPasswordDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.SetPassword(dto!));
    }

    /// <summary>
    /// POST api/user/forgot-password → UserController.ForgotPassword
    /// </summary>
    [Function("User_ForgotPassword")]
    public async Task<IActionResult> User_ForgotPassword(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/user/forgot-password")] HttpRequest req)
    {
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // No authentication required ([AllowAnonymous])

        var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.User.ForgotPasswordDto>(
            req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);

        return FunctionResultHelper.Normalize(await _controller.ForgotPassword(dto!));
    }

    /// <summary>
    /// GET api/user/validate-invitation → UserController.ValidateInvitationToken
    /// </summary>
    [Function("User_ValidateInvitationToken")]
    public async Task<IActionResult> User_ValidateInvitationToken(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/user/validate-invitation")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // No authentication required ([AllowAnonymous] or no [Authorize])

        string token = req.Query["token"].ToString() ?? "";

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.ValidateInvitationToken(token));
    }
}
