// <auto-generated/>
// This file was auto-generated by Fakvio.Functions.Generator.
// To regenerate, run the Fakvio.Functions.Generator console app.
// Source controller: Fakvio.API.Controller.VatRateController

#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Fakvio.API.Controller;
using Fakvio.Contracts.Dto.VatRate;

namespace Fakvio.Functions.Generated;

/// <summary>
/// Auto-generated Azure Functions HTTP triggers wrapping VatRateController.
/// Each public [Http*] action method is exposed as a separate Azure Function.
/// The controller is injected via DI and receives the current HttpContext
/// so it has access to User claims, request data, etc.
/// </summary>
public class VatRateFunctions
{
    private readonly VatRateController _controller;

    /// <summary>
    /// Constructor — the controller is resolved from the DI container.
    /// AddControllersAsServices() in Program.cs enables this injection pattern.
    /// </summary>
    public VatRateFunctions(VatRateController controller)
    {
        _controller = controller;
    }

    /// <summary>
    /// GET api/vatrate → VatRateController.GetAllVatRates
    /// </summary>
    [Function("VatRate_GetAllVatRates")]
    public async Task<IActionResult> VatRate_GetAllVatRates(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/vatrate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        bool.TryParse(req.Query["includeInactive"], out var includeInactive);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetAllVatRates(includeInactive, cancellationToken));
    }

    /// <summary>
    /// GET api/vatrate/{id} → VatRateController.GetVatRateById
    /// </summary>
    [Function("VatRate_GetVatRateById")]
    public async Task<IActionResult> VatRate_GetVatRateById(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/vatrate/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetVatRateById(__id_parsed, cancellationToken));
    }

    /// <summary>
    /// GET api/vatrate/active → VatRateController.GetActiveVatRatesForDate
    /// </summary>
    [Function("VatRate_GetActiveVatRatesForDate")]
    public async Task<IActionResult> VatRate_GetActiveVatRatesForDate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/vatrate/active")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        DateTime? date = DateTime.TryParse(req.Query["date"], out var _dateParsed) ? _dateParsed : null;
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetActiveVatRatesForDate(date, cancellationToken));
    }

    /// <summary>
    /// GET api/vatrate/default/standard → VatRateController.GetDefaultStandardRate
    /// </summary>
    [Function("VatRate_GetDefaultStandardRate")]
    public async Task<IActionResult> VatRate_GetDefaultStandardRate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/vatrate/default/standard")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetDefaultStandardRate(cancellationToken));
    }

    /// <summary>
    /// GET api/vatrate/default/reduced → VatRateController.GetDefaultReducedRate
    /// </summary>
    [Function("VatRate_GetDefaultReducedRate")]
    public async Task<IActionResult> VatRate_GetDefaultReducedRate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "api/vatrate/default/reduced")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.GetDefaultReducedRate(cancellationToken));
    }

    /// <summary>
    /// POST api/vatrate → VatRateController.CreateVatRate
    /// </summary>
    [Function("VatRate_CreateVatRate")]
    public async Task<IActionResult> VatRate_CreateVatRate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/vatrate")] HttpRequest req)
    {
        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → CreateVatRateDto
        var createDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.VatRate.CreateVatRateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.CreateVatRate(createDto!, cancellationToken));
    }

    /// <summary>
    /// PUT api/vatrate/{id} → VatRateController.UpdateVatRate
    /// </summary>
    [Function("VatRate_UpdateVatRate")]
    public async Task<IActionResult> VatRate_UpdateVatRate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "put", Route = "api/vatrate/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        // Deserialize request body → UpdateVatRateDto
        var updateDto = await System.Text.Json.JsonSerializer.DeserializeAsync<global::Fakvio.Contracts.Dto.VatRate.UpdateVatRateDto>(req.Body, FunctionResultHelper.JsonOptions, req.HttpContext.RequestAborted);
        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.UpdateVatRate(__id_parsed, updateDto!, cancellationToken));
    }

    /// <summary>
    /// DELETE api/vatrate/{id} → VatRateController.DeleteVatRate
    /// </summary>
    [Function("VatRate_DeleteVatRate")]
    public async Task<IActionResult> VatRate_DeleteVatRate(
        [HttpTrigger(AuthorizationLevel.Anonymous, "delete", Route = "api/vatrate/{id:long}")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.DeleteVatRate(__id_parsed, cancellationToken));
    }

    /// <summary>
    /// POST api/vatrate/{id:long}/set-default → VatRateController.SetAsDefault
    /// </summary>
    [Function("VatRate_SetAsDefault")]
    public async Task<IActionResult> VatRate_SetAsDefault(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "api/vatrate/{id:long}/set-default")] HttpRequest req,
        string id)
    {
        // Parse route parameter from string to long (Azure Functions can't bind long directly)
        if (!long.TryParse(id, out var __id_parsed))
            return new BadRequestObjectResult(new { message = "Invalid parameter 'id'." });

        // Wire up the controller's HttpContext so it can access User claims, Request, etc.
        _controller.ControllerContext = new ControllerContext { HttpContext = req.HttpContext };

        // Authorization check: [Authorize(Roles = "Admin,SysAdmin")]
        if (req.HttpContext.User.Identity?.IsAuthenticated != true)
            return new UnauthorizedResult();

        // Role check: user must be in one of [Admin,SysAdmin]
        if (!req.HttpContext.User.IsInRole("Admin") && !req.HttpContext.User.IsInRole("SysAdmin"))
            return new ForbidResult();

        var cancellationToken = req.HttpContext.RequestAborted;

        // Call the controller action and normalize the response
        return FunctionResultHelper.Normalize(await _controller.SetAsDefault(__id_parsed, cancellationToken));
    }
}
