namespace Fakvio.Application.Exceptions;

/// <summary>
/// Thrown when an XML document generated by <see cref="IVatReportService.ExportEpoVatReturnAsync"/>
/// (or any other EPO generator) fails XSD validation against the official Czech Financial
/// Administration schema.
///
/// The caller should log <see cref="ValidationErrors"/> for diagnostic purposes; EPO
/// does not accept invalid XML so the export must be aborted and the user informed.
/// </summary>
public sealed class EpoValidationException : Exception
{
    /// <summary>
    /// Individual XSD validation error messages reported by <c>XDocument.Validate()</c>.
    /// Each entry corresponds to one schema violation.
    /// </summary>
    public IReadOnlyList<string> ValidationErrors { get; }

    /// <summary>
    /// The EPO form type that failed validation (e.g. "DPHDP3").
    /// Included in <see cref="Exception.Message"/> for quick log triage.
    /// </summary>
    public string FormType { get; }

    /// <param name="formType">Human-readable form identifier, e.g. "DPHDP3".</param>
    /// <param name="errors">Non-empty list of XSD validation error messages.</param>
    public EpoValidationException(string formType, IReadOnlyList<string> errors)
        : base(BuildMessage(formType, errors))
    {
        FormType = formType;
        ValidationErrors = errors;
    }

    private static string BuildMessage(string formType, IReadOnlyList<string> errors)
    {
        // Show the first few errors in the message so the stack trace alone is useful.
        var sample = string.Join("; ", errors.Take(3));
        var suffix  = errors.Count > 3 ? $" … (+{errors.Count - 3} more)" : string.Empty;
        return $"Generated {formType} XML failed XSD validation ({errors.Count} error(s)): {sample}{suffix}";
    }
}
