using System.Globalization;
using Fakvio.API.Middleware;
using Fakvio.Application.Service;
using Fakvio.Infrastructure.Data;
using Fakvio.Infrastructure.DependencyInjection;
using Fakvio.Infrastructure.Logging;
using Fakvio.Infrastructure.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

// Set invariant culture globally so that decimal values are formatted consistently
// regardless of server locale (e.g., "21.0" instead of "21,0").
// Without this, Czech locale expects comma separator and throws FormatException.
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.InvariantCulture;

// Npgsql 10.x strictly requires DateTimeKind.Utc for "timestamp with time zone" columns.
// Blazor WASM date pickers and JSON deserialization produce DateTime with Kind=Local or Unspecified,
// which Npgsql rejects with ArgumentException. This switch restores the pre-10.x behavior
// that accepts any DateTimeKind and converts automatically.
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// ── Shared DI registrations ─────────────────────────────────────────────────
// These extension methods are defined in Fakvio.Infrastructure/DependencyInjection/
// and shared with Fakvio.Functions to eliminate code duplication.
// They register: DbContexts, application services, cloud storage, logging, auth, OAuth.
builder.Services.AddFakvioCore(builder.Configuration);
builder.Services.AddFakvioAuthentication(builder.Configuration);

// ── API-specific: Background services for log management ────────────────────
// LogFlushService: drains the DatabaseLoggerProvider queue to AppLog table every 5 seconds.
// LogCleanupService: deletes old Debug/Info logs (>48h) every hour.
// NOTE: In Azure Functions, these are replaced by timer triggers (TimerFunctions.cs).
builder.Services.AddHostedService<LogFlushService>();
builder.Services.AddHostedService<LogCleanupService>();

// ── API-specific: Controllers ───────────────────────────────────────────────
builder.Services.AddControllers();

// ── API-specific: Swagger/OpenAPI ───────────────────────────────────────────
// Provides interactive API documentation at /swagger with JWT Bearer auth support
// so developers can test authenticated endpoints directly from the Swagger UI.
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    // API metadata shown in the Swagger UI header
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Fakvio",
        Version = "v1",
        Description = "Multi-tenant invoicing API with JWT authentication. " +
                      "Use the Authorize button to paste your Bearer token."
    });

    // Include XML comments for better Swagger documentation.
    // The XML file is generated by <GenerateDocumentationFile> in the csproj.
    var xmlFiles = Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly);
    foreach (var xmlFile in xmlFiles)
    {
        options.IncludeXmlComments(xmlFile);
    }

    // Define the JWT Bearer security scheme.
    // This adds the "Authorize" button to Swagger UI where users can paste their token.
    const string bearerSchemeId = "Bearer";
    options.AddSecurityDefinition(bearerSchemeId, new OpenApiSecurityScheme
    {
        Description = "Enter your JWT token (without the 'Bearer' prefix)",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",   // lowercase per RFC 7235
        BearerFormat = "JWT"
    });

    // Apply the JWT Bearer requirement globally to all endpoints.
    // Individual endpoints can override this with [AllowAnonymous].
    options.AddSecurityRequirement(document =>
        new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference(bearerSchemeId, document)] = new List<string>()
        });
});

// ── API-specific: CORS ──────────────────────────────────────────────────────
// Restrict to configured origins (no more AllowAnyOrigin).
// Origins are loaded from CorsSettings:AllowedOrigins in appsettings.json.
// Development overrides allow localhost; production requires explicit domain(s).
var allowedOrigins = builder.Configuration.GetSection("CorsSettings:AllowedOrigins").Get<string[]>() ?? [];

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            // Production / Development: only allow configured origins
            policy.WithOrigins(allowedOrigins)
                  .AllowAnyMethod()
                  .AllowAnyHeader()
                  // Expose X-Correlation-Id so browser JavaScript (Blazor WASM) can read the
                  // CorrelationId from the response header for client-side debugging/logging.
                  .WithExposedHeaders("X-Correlation-Id")
                  .AllowCredentials(); // Required for cookie-based auth and SignalR
        }
        else
        {
            // Fallback: no origins configured — block all cross-origin requests
            policy.SetIsOriginAllowed(_ => false)
                  .AllowAnyMethod()
                  .AllowAnyHeader();
        }
    });
});

var app = builder.Build();

// ── Startup migrations ──────────────────────────────────────────────────────
// Apply database migrations automatically on startup.
// Step 1: Migrate the master database (Users, Companies, CompanySystemSettings, code tables).
// Step 2: Tenant migrations are handled LAZILY by ITenantDbContextFactory.EnsureMigratedAsync
//         — each tenant schema is migrated on first request (cached per process lifetime).
//         This is faster at startup and handles tenants provisioned while the app is running.
// Skip during integration tests — InMemoryDatabase does not support migrations.
if (!app.Environment.IsEnvironment("Testing"))
{
    using (var scope = app.Services.CreateScope())
    {
        // Master DB migrations — always applied first
        var masterDb = scope.ServiceProvider.GetRequiredService<MasterDbContext>();
        await masterDb.Database.MigrateAsync();

        // FOR DEVELOPMENT ONLY - delete all dbs and start fresh on each run. Comment out in production!
        //var provisioningService = scope.ServiceProvider.GetRequiredService<ITenantProvisioningService>();
        //await provisioningService.DeleteAllTenantDbs();
        //await masterDb.Database.EnsureDeletedAsync();
        //await masterDb.Database.MigrateAsync();
    }
}

// ── HTTP pipeline ───────────────────────────────────────────────────────────

// CorrelationId MUST be the first middleware — before Swagger, CORS, Auth, etc.
// This ensures every log entry (including CORS errors and auth failures) has a CorrelationId.
app.UseCorrelationId();

//if (app.Environment.IsDevelopment())
//{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "Fakvio v1");
        options.RoutePrefix = string.Empty; // Swagger at root URL
    });
//}

app.UseCors();

// HTTPS redirect breaks CORS in development — the browser follows the redirect
// to https://localhost:7047 which is a different origin than http://localhost:5237,
// causing "No Access-Control-Allow-Origin" errors on the redirected request.
if (!app.Environment.IsDevelopment())
{
    app.UseHttpsRedirection();
}

// Authentication must come before Authorization
app.UseAuthentication();
app.UseAuthorization();

// Impersonation middleware — allows SysAdmin to act as a specific company
// by sending X-Company-Id header. Must be after auth so we can check the role.
app.UseImpersonation();

// Tenant context middleware — validates that authenticated users have a valid,
// provisioned, and active tenant for tenant-scoped API endpoints.
// Skips master-only paths (/api/auth, /api/user, /api/company, /swagger, /health).
// Must be after UseImpersonation so the CompanyId claim is already set.
app.UseTenantContext();

app.MapControllers();

await app.RunAsync();

// Required for WebApplicationFactory<Program> in integration tests.
// The top-level statements file doesn't expose a named class by default,
// so this partial declaration makes the implicit Program class accessible.
public partial class Program { }
