using System.Globalization;
using Fakvio.API.Middleware;
using Fakvio.API.Telemetry;
using Fakvio.Application.Service;
using Fakvio.Infrastructure.Data;
using Fakvio.Infrastructure.DependencyInjection;
using Fakvio.Infrastructure.Logging;
using Fakvio.Infrastructure.Service;
using Fakvio.Infrastructure.Tailscale;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

// Set invariant culture globally so that decimal values are formatted consistently
// regardless of server locale (e.g., "21.0" instead of "21,0").
// Without this, Czech locale expects comma separator and throws FormatException.
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.InvariantCulture;

// Npgsql 10.x strictly requires DateTimeKind.Utc for "timestamp with time zone" columns.
// Blazor WASM date pickers and JSON deserialization produce DateTime with Kind=Local or Unspecified,
// which Npgsql rejects with ArgumentException. This switch restores the pre-10.x behavior
// that accepts any DateTimeKind and converts automatically.
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// ── Shared DI registrations ─────────────────────────────────────────────────
// These extension methods are defined in Fakvio.Infrastructure/DependencyInjection/
// and shared with the MigrationTool and the test hosts.
// They register: DbContexts, application services, cloud storage, logging, auth, OAuth.
builder.Services.AddFakvioCore(builder.Configuration);
builder.Services.AddFakvioAuthentication(builder.Configuration);

// ── Background services ─────────────────────────────────────────────────────
// LogFlushService: drains the DatabaseLoggerProvider queue to AppLog table every 20 seconds.
// LogCleanupService: deletes old Debug/Info logs (>48h) every hour.
// ReminderWorker: daily dunning at 06:00 UTC. (ImapPollWorker is registered by AddFakvioCore.)
// All of them need "Always On" on the App Service — an idle-recycled process runs nothing.
builder.Services.AddHostedService<LogFlushService>();
builder.Services.AddHostedService<LogCleanupService>();
builder.Services.AddHostedService<ReminderWorker>();

// ── Application Insights ────────────────────────────────────────────────────
// Reads APPLICATIONINSIGHTS_CONNECTION_STRING from the App Service settings; without it
// (local dev, tests) the SDK stays quiet. CorrelationIdTelemetryInitializer stamps our
// user-facing CorrelationId on every telemetry item so a browser-reported id can be
// searched in App Insights: customDimensions.CorrelationId == "guid".
builder.Services.AddApplicationInsightsTelemetry();
builder.Services.AddHttpContextAccessor();
builder.Services.AddSingleton<ITelemetryInitializer, CorrelationIdTelemetryInitializer>();

// ── API-specific: Controllers ───────────────────────────────────────────────
builder.Services.AddControllers();

// ── API-specific: Swagger/OpenAPI ───────────────────────────────────────────
// Provides interactive API documentation at /swagger with JWT Bearer auth support
// so developers can test authenticated endpoints directly from the Swagger UI.
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    // API metadata shown in the Swagger UI header
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Fakvio",
        Version = "v1",
        Description = "Multi-tenant invoicing API with JWT authentication. " +
                      "Use the Authorize button to paste your Bearer token."
    });

    // Include XML comments for better Swagger documentation.
    // The XML file is generated by <GenerateDocumentationFile> in the csproj.
    var xmlFiles = Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly);
    foreach (var xmlFile in xmlFiles)
    {
        options.IncludeXmlComments(xmlFile);
    }

    // Define the JWT Bearer security scheme.
    // This adds the "Authorize" button to Swagger UI where users can paste their token.
    const string bearerSchemeId = "Bearer";
    options.AddSecurityDefinition(bearerSchemeId, new OpenApiSecurityScheme
    {
        Description = "Enter your JWT token (without the 'Bearer' prefix)",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",   // lowercase per RFC 7235
        BearerFormat = "JWT"
    });

    // Apply the JWT Bearer requirement globally to all endpoints.
    // Individual endpoints can override this with [AllowAnonymous].
    options.AddSecurityRequirement(document =>
        new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference(bearerSchemeId, document)] = new List<string>()
        });
});

// ── API-specific: CORS ──────────────────────────────────────────────────────
// Restrict to configured origins (no more AllowAnyOrigin).
// Origins are loaded from CorsSettings:AllowedOrigins in appsettings.json.
// Development overrides allow localhost; production requires explicit domain(s).
var allowedOrigins = builder.Configuration.GetSection("CorsSettings:AllowedOrigins").Get<string[]>() ?? [];

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            // Production / Development: only allow configured origins
            policy.WithOrigins(allowedOrigins)
                  .AllowAnyMethod()
                  .AllowAnyHeader()
                  // Expose X-Correlation-Id so browser JavaScript (Blazor WASM) can read the
                  // CorrelationId from the response header for client-side debugging/logging.
                  .WithExposedHeaders("X-Correlation-Id")
                  .AllowCredentials(); // Required for cookie-based auth and SignalR
        }
        else
        {
            // Fallback: no origins configured — block all cross-origin requests
            policy.SetIsOriginAllowed(_ => false)
                  .AllowAnyMethod()
                  .AllowAnyHeader();
        }
    });
});

var app = builder.Build();

// Startup breadcrumb: which database auth mode won, and from which config key. Logged
// BEFORE the migrations below, because that is the step that fails when the database is
// unreachable — and an unreachable database also means no SysAdmin login and therefore no
// /api/diagnostic/health to ask instead. See LogDatabaseAuthMode + SELFHOST-DB.md §3.4.
app.Services.LogDatabaseAuthMode();

// ── Tailscale tunnel + startup migration (background) ───────────────────────
// The database sits behind Tailscale and its port is not on the public internet, so the
// connection string points at a loopback port that only exists once the tunnel is up.
//
// WHY a background task and not an IHostedService: hosted services do not start until RunAsync()
// below, and the migration — the very first socket the app opens — has to wait for the tunnel.
// WHY not awaited before RunAsync(): a tunnel bring-up can legitimately take 100 s (three login
// attempts) and App Service's startup probe would give up on a process that binds its port that
// late. So the tunnel and the migration run as one background task, Kestrel starts immediately,
// and requests that arrive before the database is reachable get 503 + Retry-After from
// StartupGateMiddleware instead of a connection timeout.
// It has to be after Build(), because that is where the real ILogger and
// IHostApplicationLifetime come from.
//
// Without TAILSCALE_AUTHKEY there is nothing to wait for, so local development and the test
// hosts (which reach their database directly) migrate synchronously before the first request,
// exactly as before.
//
// Tenant migrations are handled LAZILY by ITenantDbContextFactory.EnsureMigratedAsync — each
// tenant schema is migrated on first request (cached per process lifetime).
var tunnelLogger = app.Services.GetRequiredService<ILoggerFactory>().CreateLogger("Fakvio.API.Tailscale");
var tunnelLifetime = app.Services.GetRequiredService<IHostApplicationLifetime>();
var tailscaleAuthKey = Environment.GetEnvironmentVariable(TailscaleTunnel.AuthKeyEnv);

async Task BringUpDatabaseAsync()
{
    try
    {
        try
        {
            // ApplicationStopping shortens the tunnel's own startup budget: a shutdown requested
            // while the node is still logging in must not wait out the full budget before the
            // host can exit.
            await TailscaleTunnel.StartIfConfiguredAsync(
                tailscaleAuthKey,
                tunnelLifetime,
                tunnelLogger,
                tunnelLifetime.ApplicationStopping);
        }
        catch (Exception ex)
        {
            // Do not crash the host: the health endpoint should still answer so the failure is
            // diagnosable. The migration below will fail too and say the same thing.
            tunnelLogger.LogError(ex, "Startup: Tailscale tunnel failed — database unreachable until resolved");
        }

        try
        {
            using var scope = app.Services.CreateScope();
            var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
            var masterDb = scope.ServiceProvider.GetRequiredService<MasterDbContext>();

            // Skip for non-relational providers. Integration tests swap PostgreSQL for the EF Core
            // InMemory provider, which has no migration history and throws on MigrateAsync().
            // The check is on the provider itself rather than on an environment name, so any test
            // host works regardless of which ASPNETCORE_ENVIRONMENT it needs to simulate.
            if (masterDb.Database.IsRelational())
            {
                logger.LogInformation("Startup: applying master database migrations...");
                await masterDb.Database.MigrateAsync();
                logger.LogInformation("Startup: master database migrated successfully");
                // Recorded so /api/diagnostic/health can report it.
                StartupState.MarkMigration(succeeded: true);
            }
        }
        catch (Exception ex)
        {
            // Log but don't crash — background workers and the health endpoint should still work
            // even if the database isn't ready yet.
            tunnelLogger.LogError(ex, "Startup: database migration failed — API calls will return errors until resolved");
            StartupState.MarkMigration(succeeded: false, error: ex.GetBaseException().Message);
        }
    }
    finally
    {
        // Open the startup gate only once BOTH the tunnel and the migration are over: a request
        // let through after the tunnel but before MigrateAsync() would run against a schema that
        // is still missing this release's columns. Opened even when either step FAILED, because
        // a gate that stays closed would replace a diagnosable error with a silent blackout.
        // See StartupState.
        StartupState.MarkDatabaseReady();
    }
}

if (string.IsNullOrWhiteSpace(tailscaleAuthKey))
{
    // No tunnel to wait for (local dev, integration tests): migrate synchronously before the
    // first request, exactly as this host always did. Avoids the race where the test client's
    // first request lands before the background task has even been scheduled.
    await BringUpDatabaseAsync();
}
else
{
    _ = Task.Run(BringUpDatabaseAsync);
}

// ── HTTP pipeline ───────────────────────────────────────────────────────────

// CorrelationId MUST be the first middleware — before Swagger, CORS, Auth, etc.
// This ensures every log entry (including CORS errors and auth failures) has a CorrelationId.
app.UseCorrelationId();

// GlobalExceptionHandler is the SECOND middleware — right after CorrelationId so that
// the CorrelationId is already set in HttpContext.Items when an exception is caught,
// and so it wraps the entire remaining pipeline (Swagger, CORS, Auth, controllers, etc.).
app.UseGlobalExceptionHandler();

// Swagger is a DEVELOPMENT-ONLY convenience. Outside Development neither the UI nor
// swagger.json is registered at all, so those paths simply 404 — the full API surface
// (route table, DTO shapes, auth scheme) is never published to the public internet.
// The guard is on the hosting environment, not on configuration, so a mis-set config
// value cannot switch it back on in Production.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "Fakvio v1");
        options.RoutePrefix = string.Empty; // Swagger at root URL
    });
}

app.UseCors();

// Startup gate — must run BEFORE the auth and tenant middleware: every one of those touches
// the master database, so gating after them would still hit the connection that is not ready
// yet. Until the tunnel's forwarder has bound its loopback port, API requests get 503 +
// Retry-After instead of a 15 s timeout and a 500. After CORS so the 503 carries CORS headers.
app.UseStartupGate();

// HTTPS redirect breaks CORS in development — the browser follows the redirect
// to https://localhost:7047 which is a different origin than http://localhost:5237,
// causing "No Access-Control-Allow-Origin" errors on the redirected request.
if (!app.Environment.IsDevelopment())
{
    app.UseHttpsRedirection();
}

// Authentication must come before Authorization
app.UseAuthentication();
app.UseAuthorization();

// API-key scope middleware — a read-only key gets 403 on state-changing requests,
// and no key may manage keys. Must be after UseAuthentication so the scope claim exists;
// JWT requests carry no scope claim and pass straight through.
app.UseApiKeyScope();

// Impersonation middleware — allows SysAdmin to act as a specific company
// by sending X-Company-Id header. Must be after auth so we can check the role.
app.UseImpersonation();

// Tenant context middleware — validates that authenticated users have a valid,
// provisioned, and active tenant for tenant-scoped API endpoints.
// Skips master-only paths (/api/auth, /api/user, /api/company, /swagger, /health).
// Must be after UseImpersonation so the CompanyId claim is already set.
app.UseTenantContext();

app.MapControllers();

await app.RunAsync();

// Required for WebApplicationFactory<Program> in integration tests.
// The top-level statements file doesn't expose a named class by default,
// so this partial declaration makes the implicit Program class accessible.
public partial class Program { }
