using System.Globalization;
using System.Threading.RateLimiting;
using Fakvio.API.Middleware;
using Fakvio.API.Telemetry;
using Fakvio.Application.Service;
using Fakvio.Infrastructure.Data;
using Fakvio.Infrastructure.DependencyInjection;
using Fakvio.Infrastructure.Logging;
using Fakvio.Infrastructure.Service;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

// Set invariant culture globally so that decimal values are formatted consistently
// regardless of server locale (e.g., "21.0" instead of "21,0").
// Without this, Czech locale expects comma separator and throws FormatException.
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.InvariantCulture;

// Npgsql 10.x strictly requires DateTimeKind.Utc for "timestamp with time zone" columns.
// Blazor WASM date pickers and JSON deserialization produce DateTime with Kind=Local or Unspecified,
// which Npgsql rejects with ArgumentException. This switch restores the pre-10.x behavior
// that accepts any DateTimeKind and converts automatically.
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// ── Shared DI registrations ─────────────────────────────────────────────────
// These extension methods are defined in Fakvio.Infrastructure/DependencyInjection/
// and shared with the MigrationTool and the test hosts.
// They register: DbContexts, application services, cloud storage, logging, auth, OAuth.
builder.Services.AddFakvioCore(builder.Configuration);
builder.Services.AddFakvioAuthentication(builder.Configuration);

// ── Background services ─────────────────────────────────────────────────────
// LogFlushService: drains the DatabaseLoggerProvider queue to AppLog table every 20 seconds.
// LogCleanupService: deletes old Debug/Info logs (>48h) every hour.
// ReminderWorker: daily dunning at 06:00 UTC. (ImapPollWorker is registered by AddFakvioCore.)
// All of them need "Always On" on the App Service — an idle-recycled process runs nothing.
builder.Services.AddHostedService<LogFlushService>();
builder.Services.AddHostedService<LogCleanupService>();
builder.Services.AddHostedService<ReminderWorker>();
builder.Services.AddHostedService<RecurringInvoiceWorker>();

// ── Application Insights ────────────────────────────────────────────────────
// Reads APPLICATIONINSIGHTS_CONNECTION_STRING from the App Service settings; without it
// (local dev, tests) the SDK stays quiet. CorrelationIdTelemetryInitializer stamps our
// user-facing CorrelationId on every telemetry item so a browser-reported id can be
// searched in App Insights: customDimensions.CorrelationId == "guid".
builder.Services.AddApplicationInsightsTelemetry();
builder.Services.AddHttpContextAccessor();
builder.Services.AddSingleton<ITelemetryInitializer, CorrelationIdTelemetryInitializer>();

// ── API-specific: Controllers ───────────────────────────────────────────────
builder.Services.AddControllers();

// ── API-specific: Swagger/OpenAPI ───────────────────────────────────────────
// Provides interactive API documentation at /swagger with JWT Bearer auth support
// so developers can test authenticated endpoints directly from the Swagger UI.
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    // API metadata shown in the Swagger UI header
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Fakvio",
        Version = "v1",
        Description = "Multi-tenant invoicing API with JWT authentication. " +
                      "Use the Authorize button to paste your Bearer token."
    });

    // Include XML comments for better Swagger documentation.
    // The XML file is generated by <GenerateDocumentationFile> in the csproj.
    var xmlFiles = Directory.GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly);
    foreach (var xmlFile in xmlFiles)
    {
        options.IncludeXmlComments(xmlFile);
    }

    // Define the JWT Bearer security scheme.
    // This adds the "Authorize" button to Swagger UI where users can paste their token.
    const string bearerSchemeId = "Bearer";
    options.AddSecurityDefinition(bearerSchemeId, new OpenApiSecurityScheme
    {
        Description = "Enter your JWT token (without the 'Bearer' prefix)",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",   // lowercase per RFC 7235
        BearerFormat = "JWT"
    });

    // Apply the JWT Bearer requirement globally to all endpoints.
    // Individual endpoints can override this with [AllowAnonymous].
    options.AddSecurityRequirement(document =>
        new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference(bearerSchemeId, document)] = new List<string>()
        });
});

// ── API-specific: CORS ──────────────────────────────────────────────────────
// Restrict to configured origins (no more AllowAnyOrigin).
// Origins are loaded from CorsSettings:AllowedOrigins in appsettings.json.
// Development overrides allow localhost; production requires explicit domain(s).
var allowedOrigins = builder.Configuration.GetSection("CorsSettings:AllowedOrigins").Get<string[]>() ?? [];

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            // Production / Development: only allow configured origins
            policy.WithOrigins(allowedOrigins)
                  .AllowAnyMethod()
                  .AllowAnyHeader()
                  // Expose X-Correlation-Id so browser JavaScript (Blazor WASM) can read the
                  // CorrelationId from the response header for client-side debugging/logging.
                  .WithExposedHeaders("X-Correlation-Id")
                  .AllowCredentials(); // Required for cookie-based auth and SignalR
        }
        else
        {
            // Fallback: no origins configured — block all cross-origin requests
            policy.SetIsOriginAllowed(_ => false)
                  .AllowAnyMethod()
                  .AllowAnyHeader();
        }
    });
});

// ── Forwarded headers (Azure App Service front-end) ─────────────────────────
// Fakvio.API runs on Azure App Service. The platform's own front-end/edge is the ONLY
// network path into this container — there is no way for a caller to open a TCP
// connection straight to our Kestrel process, so whatever connects to us has already
// gone through Azure's own reverse proxy. That proxy's own address is a private Azure
// address, NOT loopback (127.0.0.1) — the "App Service front-end talks to Kestrel over
// loopback" assumption holds for IIS in-process hosting on Windows, but not for the
// platform's own edge layer this middleware needs to trust.
//
// ForwardedHeadersOptions' default KnownProxies/KnownNetworks only contains loopback,
// so leaving it untouched would mean the middleware never trusts Azure's edge, never
// applies X-Forwarded-For, and every request would show the SAME RemoteIpAddress (the
// edge's own address) — collapsing the "auth-anon" limiter below from per-IP into one
// single global bucket shared by every visitor (one burst from anywhere would 429 lock
// out all real logins). Clearing KnownNetworks/KnownProxies here is what many
// Microsoft-documented Azure App Service / containerized-hosting samples do for exactly
// this reason, and it is safe ONLY because of the point above: nothing but Azure's own
// edge can ever be the thing connecting to Kestrel.
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
    // Only the right-most X-Forwarded-For entry is used - the one the Azure front-end appends.
    // Anything to its left came from the client and is spoofable, so never raise this limit
    // (a spoofed IP would let an attacker get a fresh rate-limit bucket per request).
    options.ForwardLimit = 1;
});

// ── Rate limiting for anonymous auth endpoints (RC.4) ────────────────────────
// reCAPTCHA (CaptchaService) is the only gate on login/register/ares/forgot-password/
// set-password/validate-invitation/2FA-verify, and it can be starved by an ad blocker
// (the token then comes back empty and the gate fails closed — safe, but each attempt
// still costs a request). A per-IP fixed window on top bounds the attempt rate itself,
// independent of whether the CAPTCHA gate lets a given request through.
// Limits are configurable (RateLimiting:AuthAnon in appsettings.json) — bump them if a
// legitimate flow (e.g. shared office IP) hits the ceiling in practice.
//
// ponytail: this counter is per PROCESS, not shared across App Service replicas — with
// N running instances an attacker effectively gets PermitLimit x N, and which instance
// answers a given request is up to Azure's load balancer. Fine at today's scale (single
// instance); if/when this app scales out and that matters, move the counter to a shared
// store (e.g. a distributed rate limiter backed by the existing PostgreSQL or Redis) —
// don't reach for that now for a service with no replicas.
var authAnonRateLimitConfig = builder.Configuration.GetSection("RateLimiting:AuthAnon");
var authAnonPermitLimit = authAnonRateLimitConfig.GetValue("PermitLimit", 10);
var authAnonWindowSeconds = authAnonRateLimitConfig.GetValue("WindowSeconds", 60);

builder.Services.AddRateLimiter(options =>
{
    // 429 + Retry-After (RFC 6585) — the Blazor UI checks for 429 specifically to show
    // its own localized "too many attempts" message instead of a generic error.
    options.OnRejected = async (context, cancellationToken) =>
    {
        context.HttpContext.Response.Headers.RetryAfter = authAnonWindowSeconds.ToString();
        context.HttpContext.Response.StatusCode = StatusCodes.Status429TooManyRequests;
        await context.HttpContext.Response.WriteAsJsonAsync(
            new { message = "Too many attempts. Please try again later." },
            cancellationToken);
    };

    options.AddPolicy("auth-anon", context =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: GetClientIpPartitionKey(context),
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = authAnonPermitLimit,
                Window = TimeSpan.FromSeconds(authAnonWindowSeconds),
                QueueLimit = 0 // Reject immediately once the window is full — do not make callers wait in a queue.
            }));
});

var app = builder.Build();

// Forwarded headers must run before anything that reads the client IP or scheme —
// first middleware in the pipeline, per Microsoft's own guidance for reverse-proxy setups.
app.UseForwardedHeaders();

// Startup breadcrumb: which database auth mode won, and from which config key. Logged
// BEFORE the migrations below, because that is the step that fails when the database is
// unreachable — and an unreachable database also means no SysAdmin login and therefore no
// /api/diagnostic/health to ask instead. See LogDatabaseAuthMode + SELFHOST-DB.md §3.4.
app.Services.LogDatabaseAuthMode();

// ── Startup migration (master DB) ───────────────────────────────────────────
// Applied synchronously before the first request. Tenant schemas are migrated LAZILY by
// ITenantDbContextFactory.EnsureMigratedAsync on their first request (cached per process).
//
// A failure is logged and recorded (StartupState → /api/diagnostic/health) instead of
// crashing the host: a crash-looping App Service container answers 503 with no clue why,
// while a running host still serves the health endpoint and App Insights gets the error.
using (var scope = app.Services.CreateScope())
{
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
    try
    {
        var masterDb = scope.ServiceProvider.GetRequiredService<MasterDbContext>();

        // Skip for non-relational providers. Integration tests swap PostgreSQL for the EF Core
        // InMemory provider, which has no migration history and throws on MigrateAsync().
        // The check is on the provider itself rather than on an environment name, so any test
        // host works regardless of which ASPNETCORE_ENVIRONMENT it needs to simulate.
        if (masterDb.Database.IsRelational())
        {
            logger.LogInformation("Startup: applying master database migrations...");
            await masterDb.Database.MigrateAsync();
            logger.LogInformation("Startup: master database migrated successfully");
            StartupState.MarkMigration(succeeded: true);
        }
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Startup: database migration failed — API calls will return errors until resolved");
        StartupState.MarkMigration(succeeded: false, error: ex.GetBaseException().Message);
    }
}

// ── HTTP pipeline ───────────────────────────────────────────────────────────

// CorrelationId MUST be the first middleware — before Swagger, CORS, Auth, etc.
// This ensures every log entry (including CORS errors and auth failures) has a CorrelationId.
app.UseCorrelationId();

// GlobalExceptionHandler is the SECOND middleware — right after CorrelationId so that
// the CorrelationId is already set in HttpContext.Items when an exception is caught,
// and so it wraps the entire remaining pipeline (Swagger, CORS, Auth, controllers, etc.).
app.UseGlobalExceptionHandler();

// Swagger is a DEVELOPMENT-ONLY convenience. Outside Development neither the UI nor
// swagger.json is registered at all, so those paths simply 404 — the full API surface
// (route table, DTO shapes, auth scheme) is never published to the public internet.
// The guard is on the hosting environment, not on configuration, so a mis-set config
// value cannot switch it back on in Production.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "Fakvio v1");
        options.RoutePrefix = string.Empty; // Swagger at root URL
    });
}

app.UseCors();

// HTTPS redirect breaks CORS in development — the browser follows the redirect
// to https://localhost:7047 which is a different origin than http://localhost:5237,
// causing "No Access-Control-Allow-Origin" errors on the redirected request.
if (!app.Environment.IsDevelopment())
{
    app.UseHttpsRedirection();
}

// Authentication must come before Authorization
app.UseAuthentication();
app.UseAuthorization();

// API-key scope middleware — a read-only key gets 403 on state-changing requests,
// and no key may manage keys. Must be after UseAuthentication so the scope claim exists;
// JWT requests carry no scope claim and pass straight through.
app.UseApiKeyScope();

// Impersonation middleware — allows SysAdmin to act as a specific company
// by sending X-Company-Id header. Must be after auth so we can check the role.
app.UseImpersonation();

// Tenant context middleware — validates that authenticated users have a valid,
// provisioned, and active tenant for tenant-scoped API endpoints.
// Skips master-only paths (/api/auth, /api/user, /api/company, /swagger, /health).
// Must be after UseImpersonation so the CompanyId claim is already set.
app.UseTenantContext();

// Rate limiter — enforces the "auth-anon" policy on endpoints tagged with
// [EnableRateLimiting("auth-anon")] (login, register, ares, forgot-password,
// set-password, validate-invitation, 2FA verify). Endpoints without the attribute are
// unaffected. Must come after UseForwardedHeaders (top of pipeline) so the partition
// key below sees the real client IP, not Azure's front-end.
app.UseRateLimiter();

app.MapControllers();

await app.RunAsync();

// Partition key for the "auth-anon" rate limiter policy: the caller's IP address.
// Falls back to a single shared "unknown" bucket when no IP is available at all (some
// test hosts have no Connection.RemoteIpAddress) — every such caller then shares one
// limit, which is a safe default and never happens in production behind Azure.
static string GetClientIpPartitionKey(HttpContext context)
    => context.Connection.RemoteIpAddress?.ToString() ?? "unknown";

// Required for WebApplicationFactory<Program> in integration tests.
// The top-level statements file doesn't expose a named class by default,
// so this partial declaration makes the implicit Program class accessible.
public partial class Program { }
