using System.Text;
using Fakvio.Contracts.Dto.Readiness;
using Fakvio.Domain.Enums;
using Fakvio.UI.Shared.Components.Shared;
using Microsoft.Extensions.Localization;

namespace Fakvio.UI.Shared.Components.Chat;

/// <summary>
/// Decides whether a tenant needs conversational onboarding and composes the assistant's
/// proactive welcome (issue #214, story #150).
///
/// Why the assistant greets first: the primary onboarding path in this app is a conversation,
/// not a stepper. A tenant whose settings are unfinished would otherwise land on a dashboard
/// that shows nothing and says nothing about what to do next.
///
/// The welcome text itself is composed here, NOT generated by the AI — the panel can show it
/// the moment it opens, it costs no tokens, it cannot hallucinate what is missing, and it is
/// testable without a live model. Once the user answers, the real conversation takes over:
/// the server prompt carries the same gaps plus the onboarding instructions
/// (<c>AiSystemPrompt.OnboardingInstructions</c>), which is what makes the assistant ask for
/// one value at a time and write it through the chat tools.
///
/// A pure function on purpose — no component, no injected state — so the rule "unfinished
/// setup ⇒ greet, finished setup ⇒ stay quiet" is unit testable without rendering anything.
/// </summary>
public static class ChatOnboarding
{
    /// <summary>
    /// Builds the proactive welcome for a readiness report, or null when there is nothing
    /// to onboard — the caller uses null as "do not open the panel, do not greet".
    ///
    /// Only <see cref="EReadinessSeverity.Blocking"/> findings count, exactly as in the
    /// system prompt: a warning does not stop the user from invoicing, so opening the chat
    /// over one would be an interruption without a purpose.
    /// </summary>
    /// <param name="report">Report from <c>GET /api/readiness</c> for the whole tenant.</param>
    /// <param name="localizer">Shared UI localizer — the welcome is user-facing text.</param>
    /// <returns>Markdown for one assistant message, or null when the tenant is ready.</returns>
    public static string? BuildWelcome(ReadinessReportDto report, IStringLocalizer<SharedResource> localizer)
    {
        var blocking = report.Issues
            .Where(i => i.Severity == EReadinessSeverity.Blocking)
            .ToList();

        if (blocking.Count == 0)
            return null;

        // Markdown, because assistant bubbles are rendered through MarkdownView — the list
        // then looks the same as anything the model itself would send.
        var sb = new StringBuilder();
        sb.AppendLine(localizer["Chat_Onboarding_Intro"].Value);
        sb.AppendLine();

        foreach (var issue in blocking)
        {
            // The banner shows the missing fields on a line of their own; a chat bullet has no
            // such line, so they follow a dash. Without them "no sequence for this document type"
            // would not say WHICH document type.
            var fields = ReadinessIssueText.DescribeMissingFields(localizer, issue);
            var text = ReadinessIssueText.Describe(localizer, issue);
            sb.AppendLine(fields.Length == 0 ? $"- {text}" : $"- {text} — {fields}");
        }

        sb.AppendLine();
        sb.Append(localizer["Chat_Onboarding_Ask"].Value);

        return sb.ToString();
    }
}
