namespace Fakvio.Domain.Enums;

/// <summary>
/// Role of a message in a chat conversation.
/// Determines how the message is displayed and processed by AI providers.
/// </summary>
public enum EChatRole
{
    /// <summary>
    /// System instructions — hidden from the user, sent to the AI to set behavior.
    /// Contains business context like client/invoice counts.
    /// </summary>
    System = 0,

    /// <summary>
    /// Message sent by the user (human).
    /// </summary>
    User = 1,

    /// <summary>
    /// Response generated by the AI assistant.
    /// </summary>
    Assistant = 2
}
