// <auto-generated />
// This file is auto-generated by EF Core tooling.
// Run: dotnet ef migrations add AddEpoTaxOfficeCode_v37 --context MasterDbContext
// to regenerate with the full BuildTargetModel snapshot.
using System;
using Fakvio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fakvio.Infrastructure.Migrations.Master
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20260502000001_AddEpoTaxOfficeCode_v37")]
    partial class AddEpoTaxOfficeCode_v37
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Full BuildTargetModel will be regenerated by: dotnet ef migrations add
            // For now, the Up()/Down() migration is correct and will be applied at runtime.
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
